name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["master"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0

      - name: Setup Ruby
        uses: ruby/setup-ruby@1a615958ad9d422dd932dc1d5823942ee002799f # v1.227.0
        with:
          ruby-version: '3.0'

      - name: Install Jekyll and Hacker Theme
        run: |
          gem install jekyll jekyll-theme-hacker

      - name: Copy README.md and LICENSE to site folder
        run: |
          cp README.md .github/sites/README.md
          cp LICENSE .github/sites/LICENSE

      - name: Replace content in README.md
        run: |
          repo_url=${{ github.server_url }}/${{ github.repository }}
          sed "s/\/LICENSE/${repo_url}\/LICENSE/g" -i .github/sites/README.md

      - name: Build Jekyll Site
        run: |
          jekyll build --source .github/sites --destination public

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
